using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IniFIleEditor.Models
{
    public enum LineSubType
    {
        InstantBuff = 0,
        SelfBuff = 1,
        BotBuff = 2,
        CombatBuff = 3,
        GroupBuff = 4,
        ProcBuffToggle = 5,
        ProcBuff,
        ProcBuffClass,
        Cure = 6,
        CureAll = 7,
        AutoRadiantToggle = 8,
        RadiantCure = 9,
        PetSpell = 10,
        PetHeal = 11,
        PetBuff = 12,
        PetTauntToggle,
        PetAutoShrinkToggle,
        PetSummonCombatToggle,
        PetBuffCombatToggle,
        LifeSupport = 13,
        Tank = 14,
        ImportantBot = 15,
        PetOwner = 16,        
        TankHeal = 17,
        XTargetHeal = 18,
        ImportantHeal = 19,
        AllHeal = 20,
        HealOverTimeSpell = 21,
        GroupHeal = 22,
        WhoToHeal = 23,
        WhoToHot = 24,
        AutoCastNecroHealOrbsToggle = 25,
        AssistType = 26,
        MeleeStickPoint = 27,
        MeleeDistance = 28,
        RangedDistance = 29,
        AutoAssistEngagePercent = 30,
        Main = 31,
        Magic = 32,
        Poison = 33,
        Disease = 34,
        BigFire = 35,
        FastFire = 36,
        LureFire = 37,
        BigCold = 38,
        FastCold = 39,
        LureCold = 40,
        BigMagic = 41,
        FastMagic = 42,
        LureMagic = 43,
        DebuffOnCommand = 44,
        DebuffOnAssist = 45,
        TargetAE = 46,
        PBAE = 47,
        QuickBurn = 48,
        LongBurn = 49,
        FullBurn = 50,
        AutoCanniToggle = 51,
        Canni = 52,
        AutoLootToggle = 53,
        AutoFood = 54,
        Food = 55,
        Drink = 56,
        Anchor = 57,
        Ability = 58,
        EvacSpell = 59,
        AutoCheetah = 60,
        Gimme = 61,
        Lifetap = 62,
        AutoRune = 63,
        AutoMez = 64,
        RuneTarget = 65,
        RuneSpell = 66,
        Mez = 67,
        Charm = 68,
        GatherManaPct = 70,
        AutoMelody = 71,
        MelodyIf = 72,
        AutoSonata = 73,
        SongPlayer = 74,
        DynamoPrecastTime = 75,
        AutoParagon = 76,
        ParagonSpell = 77,
        ParagonMana = 78,
        AutoFocusedParagon = 79,
        FocusedParagonSpell = 80,
        Character = 81,
        AxeAbility = 82,
        DivineArbitrationPct = 83,
        CelestialRegeneration = 84,
        AutoYaulp = 85,
        YaulpSpell = 86,
        AutoPetWeapons = 87,
        SummonedPetHammer = 88,
        AutoSummonOrbOfMastery = 89,
        SummonedPetItem = 90,
        LichSpell = 91,
        ManaDumpToggle = 92,
        WhoToManaDump = 93,
        ManaDump = 94,
        TargetAERangedToggle = 95,
        AutoHide = 96,
        AutoEvade = 97,
        EvadePctAggro = 98,
        SneakAttackDiscipline = 99,
        PoisonPR = 100,
        PoisonFR = 101,
        PoisonCR = 102,
        AutoHarvestToggle = 103,
        Harvest = 104,
        GroupHot,
        
    }
}
